# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'bi_stemcell'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  snowflake_spend:
    +enabled: false
  bi_stemcell:
      # Applies to all files under models/example/
    10_staging:
       +database: staging
       materialized: view
 
       stemcell__salesforce:
        +schema: stemcell__salesforce

       jaffle_shop:
        +schema: jaffle_shop
       stripe:
        +schema: stripe
       knoema:
        +schema: knoema

    20_integrate:
       +database: integrate
       materialized: view

       customer:
         +schema: customer

    30_analyze:
       +database: analyze
       materialized: table 
 
       customer:
         +schema: customer
       core:
         +schema: core    
 

